### ISSUE TITLE
Build for ARM64v8

### ISSUE THREAD

**Issue by zDEFz** [leafo/sightreading.training#113]
Current build doesn't work on ARM64v8

docker build -t sightreading.training .
Sending build context to Docker daemon  8.833MB
Step 1/5 : FROM ghcr.io/leafo/lapis-archlinux-itchio:latest
latest: Pulling from leafo/lapis-archlinux-itchio
1524aa11664f: Pull complete
aebf9300367d: Pull complete
5f5986c015b9: Pull complete
08e15b0beba8: Pull complete
c8b806dd3d09: Pull complete
648ee2f7a664: Pull complete
e33dcfd50804: Pull complete
Digest: sha256:2c8254d6ce554c53fdfb7136b5d2156f5a9bb22ca1c3a678fd9a9a4c8d1b11b6
Status: Downloaded newer image for ghcr.io/leafo/lapis-archlinux-itchio:latest
 ---> ce270e2e0ad1
Step 2/5 : MAINTAINER leaf corcoran <leafot@gmail.com>
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in aef39f02a6f6
Removing intermediate container aef39f02a6f6
 ---> 1c69a646d842
Step 3/5 : WORKDIR /site/sightreading.training
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 02da8707dd7f
Removing intermediate container 02da8707dd7f
 ---> e21b90d0a7b8
Step 4/5 : ADD . .
 ---> 169dc18a4ff5
Step 5/5 : ENTRYPOINT ./ci.sh
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 6ba97a933028
Removing intermediate container 6ba97a933028
 ---> 92235a18421e
Successfully built 92235a18421e
Successfully tagged sightreading.training:latest

**Comment by leafo** [comment]
The docker image is for the test suite, no plans to migrate the test suite to arm. You should be able to install all the dependencies locally on an arm machine, but unfortunately there is no documentation at this time.
