### ISSUE TITLE
No longer able to select Key on Staff Page

### ISSUE THREAD

**Issue by CraigAmey** [leafo/sightreading.training#123]
The Staff page Configure section has a section at the bottom for selecting the key signature. Today it is no longer working (it was working up until a day or two ago). Whatever button you click on it just stays in the key of C and that button stays shaded, only the border moves with the mouse click. I've tried both Chrome and Edge and also incognito, same result. 

![KeySelect](https://user-images.githubusercontent.com/45527943/213356912-0c696244-9f93-4f43-9a31-149fdde39563.jpg)

**Comment by leafo** [comment]
Fix is now deployed 19a4456c57a6bdd4848e1d533ae0fc019511643d sorry about the bug. You may need to hard-refresh if it doesn't immediately work after refreshing the page.

**Comment by CraigAmey** [comment]
Yes, working now. Thanks for the fix.
