### ISSUE TITLE
Key Signatures no longer work

### ISSUE THREAD

**Issue by vespaguy** [leafo/sightreading.training#124]
Hello,

The program has stopped the ability to choose different key signatures as of Jan 20th 2023. The font has also changed to a bold font. Only the key of **C** now works.

Thanks

![Sightreading issue](https://user-images.githubusercontent.com/123257065/213875528-05ec9f76-8554-44ca-b88c-85e4a8c27396.jpg)

**Comment by Albert2019Dsp** [comment]
The same here.

**Comment by Jblissdev** [comment]
Can confirm, yesterday would not work for me.

**Comment by david939david** [comment]
Doesn't work for me too. (Chrome)

**Comment by leafo** [comment]
Fix is now deployed 19a4456c57a6bdd4848e1d533ae0fc019511643d sorry about the bug. You may need to hard-refresh if it doesn't immediately work after refreshing the page.

**Comment by Albert2019Dsp** [comment]
Now it works immediately again. Even without hard refresh. Oh well, thanks a lot.
