### ISSUE TITLE
Vertical bar/measure lines incorrect for 3/4 

### ISSUE THREAD

**Issue by teadrinker** [leafo/sightreading.training#130]
I noticed this earlier but I think I understand better now:

https://sightreading.training/song/125/greensleeves

When using ts3/4 (the correct time signature), metronome is correct but _**bars are drawn incorrect**_. 
When using ts4/3 (not correct time signature), metronome is incorrect but bars are drawn correct.

**Comment by leafo** [comment]
nice catch, time signature data was not being passed through to the measure line renderer when multi-track rendering was introduced
