### ISSUE TITLE
no computer sound output windows 10 or mac sierra/high sierra

### ISSUE THREAD

**Issue by wj47** [leafo/sightreading.training#15]
app works well from interaction input point of view with M-audio key studio keyboard
however it does not appear to find midi (ms GW synth) in pc os as an output choice in windows 10 
or  midi sound generator in mac  sierra or high sierra
thank you for your efforts in creating this valuable music reading tool
wj47

**Comment by leafo** [comment]
On windows you can try the coolsoft midi mapper: https://coolsoft.altervista.org/en/forum/thread/427

I don't have OSX available so I can't test that, but you may need a similar peice of software.
