### ISSUE TITLE
Adding Augmented Chords

### ISSUE THREAD

**Issue by rvzzz** [leafo/sightreading.training#18]
Is it possible to add Augmented Chords (Both Triads and 7ths) to the `Chord` mode?:
![screen shot 2018-01-27 at 10 19 09](https://user-images.githubusercontent.com/3394457/35471026-c4f3f8a2-034b-11e8-8417-25c8eaf30c1b.png)

It seems that the `minor` option selected only generates Chords from the Natural minor Scale...
![screen shot 2018-01-27 at 10 27 43](https://user-images.githubusercontent.com/3394457/35471098-d29ab2e2-034c-11e8-9fbf-1ce8680bcdde.png)

Could we increase the select button options to have the Harmonic and Melodic ones?
![screen shot 2018-01-27 at 10 27 58](https://user-images.githubusercontent.com/3394457/35471109-0e7ceed8-034d-11e8-8a68-dd6a38bc147d.png)
![screen shot 2018-01-27 at 10 28 08](https://user-images.githubusercontent.com/3394457/35471112-11d2a28a-034d-11e8-95ba-8eb3cbadee73.png)

Although there are no different chords between the two...
This, however, doesn't occur with seventh chords...With 7th chords, the harmonic and melodic minor have different chords.

For 7th Chords, there are other different chords besides the `augmented`.
The `minMaj7` and the `fully diminished`:
![screen shot 2018-01-27 at 10 44 26](https://user-images.githubusercontent.com/3394457/35471247-4404dfaa-034f-11e8-84b3-becff69bf7c3.png)

---

The reason I say to had both is that later we could change the settings to just show roman numerals and practice that way instead of showing the letter names of the chords...

I was trying to quickly see where do you have the code for that but I can't find it...
Do you think it's a good idea?
How can I help you towards that?
Do you want me to give you the chord tones in a database query?
In what file can I add them?
Please let me know if I can help you with anything...regards!

**Comment by leafo** [comment]
Thanks for opening a ticket, I renamed minor to natural minor and then added harmonic and melodic. Give it a shot and tell me if you notice any issues.

**Comment by rvzzz** [comment]
It's perfect! :) I mean, I haven't tested it with the keyboard yet but everything seems really good! You were fast! During the next month, I will test it thoroughly. If I notice anything I will tell you. 
Thanks!
