### ISSUE TITLE
Good Job Guys

### ISSUE THREAD

**Issue by chillbrotha** [leafo/sightreading.training#20]
Please post the patreon or whatever you use to receive donations. 
Also please make it so that we can get more songs that are public domain to practice.
Lastly, make it so that you can switch between standard sheet music and the color bars for play along option.

**Comment by leafo** [comment]
Thanks for the feedback. No plans to receive donations at this time but maybe in the future.

Regarding the play along mode, I hope to make it so you can write songs and save them to your account, and share them with other people. The only songs in there right now are ones that I wrote.

Standard sheet music notation would be nice, but not sure when I'll start developing that.

Thanks
