### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by giapda** [leafo/sightreading.training#29]
Hi

i connect my m-audio keystation61 is recognized when i push but i don't ear any sound
thanks

**Comment by leafo** [comment]
This project doesn't create any sound when you play your keyboard. It only reads the notes that you play.

**Comment by BynaryCobweb** [comment]
It could actually be nice to add some sound what do you think ?

**Comment by leafo** [comment]
There's' now a build in piano sound (and wood block for metronome). It will come out with the next deploy
