### ISSUE TITLE
does not recognize flat notes

### ISSUE THREAD

**Issue by natanstr** [leafo/sightreading.training#38]
Hi!

 when I play flat notes it appears on the sheet but the notes do not move on. The note does not appear overlaid, it appear apart

![capturar](https://user-images.githubusercontent.com/43713400/46252060-85192e00-c439-11e8-8536-37db018af3c2.JPG)

Thanks!

**Comment by justinbass** [comment]
This is also happening for me on a Yamaha P45 keyboard, and in the app's keyboard on every browser tried. Reproduction: select any minor key (Bb, Eb, etc.) App will not recognize flat keys in any way. This seems like a major bug.

**Comment by rvzzz** [comment]
This happening to me too...in F Major...doing random generator...with grand staff...
![screenshot 2019-03-08 at 00 36 00](https://user-images.githubusercontent.com/3394457/53999212-8c580c80-413a-11e9-8437-302e4617304e.png)

**Comment by Garaix-Davy** [comment]
Hi! Superb app, thank you! I have the exact same issue as described above. I have connected a casio px-130 via USB onto a Windows 10 64-bit laptop using the latest Google Chrome browser. Attempted rebooting computer, keyboard, unplugging and replugging etc. Thanks for your time

**Comment by leafo** [comment]
fixed on master, will be deployed soon #70
