### ISSUE TITLE
Great for c but ....Flat/sharps not recognised!!!

### ISSUE THREAD

**Issue by cisichei** [leafo/sightreading.training#45]
So much potential with. This app- very helpful in c major but other keys don’t work!!!

**Comment by leafo** [comment]
What input device are you using? (midi keyboard, on-screen keyboard?) What page/exercise are you having an issue with? Other key signatures definitely work, so I need to know specifically what you're doing so I can debug the issue.

Thanks

**Comment by cisichei** [comment]
Hi there 
Really sorry I’m getting back to you late. Wanted to do some more testing first.

I have two setups. 
1 Korg triton - midi out to USB device - OS X (latest version) running chrome.
2 Yamaha clavinova - USB out to USB windows operating system (running chrome).
 Turns out that the no flats/sharps issue has been corrected, I assumed this was due to you debugging? 
Works on both setups but not completely reliably. I think main issue for me is when I’m running another chrome app hat uses midi (piano marvel). Regardless, I’m super grateful
For this resource and very happy to test or help In any way so let me Know if there is any testing you like me To do. 
 Really wanted to also thank you for the amazing resource you have made available.
Amazing programme - this is a game Changer and no doubt a lot of people will benefit from it. I’m a psychologist and pianist with terrible sight reading - from a cognitive processing and learning perspective, the drilling approach with direct feedback should be very effective - this reflects the cognitive overload that sight readers experience. With sufficient drilling I believe your programme should address this learning barrier so that responses become automated. The programme also has a user friendly design. 

Anyway you did not ask for a review, just very excited about this programme as I can see so many benefits and wanted to encourage you to Develop this to its full
Potential. Keep up the great work. Ps any plans for an IOx app for this?
Thanks 

Chike

**Comment by leafo** [comment]
fixed on master, will be deployed soon #70
