### ISSUE TITLE
Flats not recognized

### ISSUE THREAD

**Issue by pounia** [leafo/sightreading.training#56]
This is a wonderful little app. 
 But flats are not recognized.
Is it browser dependent ?
I've seen others had the same problems.
I do hope it will corrected. 
I use the app every day (despite the bug)

by the way : sharps are ok. I am on macbook pro, with Chrome. Using midi keyboard (bluetooth).
I've noticed that the basic random option with "chromatic" only generates natural and sharp notes.
I only get flats if i set the option to 2 or more notes. I was quite surprised the first time I saw flats, because i used the program for days without seeing one !

**Comment by pounia** [comment]
addendum : most sharps work (for me at least).
BUt some DO NOT. I've just encountered the bug on F sharps in G scale, 3 and 4 notes.

**Comment by euphonero** [comment]
ive encountered the same issue. im using chrome on a windows surface tablet, and im using a midi keyboard with a wired midi-to-usb connection to the tablet. ive noticed that when i play in keys with any flats, or when i practice chromatically, the app wont let me progress if it wants me to play a flat note. same thing happens with the note F sharp

**Comment by pounia** [comment]
I confirm. Please, oh Lord of the sightreading.training, hear our complaint, be merciful, update and correct thy mighty software. I still use it every day, despite the bug.

**Comment by tangchengcheng** [comment]
Indeed, I have also encountered the same issue. Love the app and hope it could be resolved :)

**Comment by Thomasrutgers** [comment]
Same here!

**Comment by soundscape009** [comment]
Same PLEASE FIX this software is just too amazing to not be fixed.  Also please put a pay pal donate button on the site. I would gladly donate and im certain lots of others would.

**Comment by leafo** [comment]
fixed on maser, will be deployed soon #70
