### ISSUE TITLE
Debugger notes that Web MIDI will ask for permission to use main.min.js from June 2019 on

### ISSUE THREAD

**Issue by ddTech** [leafo/sightreading.training#58]
The debugger notes that Web MIDI will ask a permission to use main.min.js from June on. 

![WebMIDI_Depeication](https://user-images.githubusercontent.com/5563573/57840009-115d4300-77c8-11e9-8fa2-2035fe8decdd.PNG)

No idea, if this will have an impact on the "app" or if Web MIDI handles this on its own.

**Comment by leafo** [comment]
It looks like they've changed how they planning to handle this https://www.chromestatus.com/feature/5138066234671104  but they haven't revealed when or how so I'm going to close this for now.

> Until today, only the latter use prompts users for permission. But to reduce security concerns, we will change this behavior to prompt permission always regardless of sysex use. This second change is still under planning, and not adopted yet.
