### ISSUE TITLE
i feel too little repetition add option to practice only a small range in staff

### ISSUE THREAD

**Issue by shimondoodkin** [leafo/sightreading.training#6]

**Comment by HansHermann123** [comment]
Hi leafo, 
I like this app very very much and I am very much interested in this request, that's exactly what I felt was missing, to be able to narrow the range of notes to a specific range of keys. 
I'd like to contribute also, however I haven't heard about moonscript or lua before. Also I am new to GitHub. So, if you are already working on this request, perfect -  if not, maybe you can help me start off with it?

**Comment by HansHermann123** [comment]
PS: other issues that I see: scroll speed control does not work in Firefox, seems to work on IE only.

**Comment by leafo** [comment]
@HansHermann123 this is only tested in chrome since it's the only browser to support web midi. Are you trying to use the on screen keyboard along with the scrolling mode? I just tested in firefox 54 and I didn't have any issues changing the speed. Keep in mind you must be in "Wait" mode to adjust the slider

**Comment by HansHermann123** [comment]
Ah ok, yes it works. Would be handy if you could also change speed while scrolling, but that's a minor thing. So, have you planned to add an option to narrow the random range? Otherwise I would look into it.

**Comment by leafo** [comment]
I've already coded basic support for it, I just haven't deployed yet. :)

**Comment by HansHermann123** [comment]
Ah cool! Any guess when you'll deploy it?

**Comment by leafo** [comment]
alright it's there now
![noterange](https://user-images.githubusercontent.com/15198/28283013-49de9ff8-6ae1-11e7-91d3-45afa11c1c7b.gif)

**Comment by HansHermann123** [comment]
Wow, really cool!!! Thanks a ton!! Makes this the no. 1 trainig tool for me :-)
