### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by littleccguy** [leafo/sightreading.training#67]
I just wanted to say thank you for this site.  It is amazing.  You should think about adding a 'Donate' button.

**Comment by leafo** [comment]
I'm planning on setting up a GithHub sponsors page if people want to donate to the project! I'll update here when it's up

**Comment by leafo** [comment]
It's available now: https://github.com/sponsors/leafo

I'll look into adding a one-off donation button at some point in the future. If that's something you''d prefer leave a comment.

Thanks

**Comment by littleccguy** [comment]
Yes, I was thinking of more of a one-off vs subscription - at least in my case anyway. thx
