### ISSUE TITLE
New item in configuration

### ISSUE THREAD

**Issue by pianogospel** [leafo/sightreading.training#7]
Hi Leaf, my name is Marcos, I'm from Brasil.

I discovered your website http://sightreading.training/ today and I'm a piano beginner.

I loved your website and I would like to ask you something, an improvement for people like me that are piano beginners.

Can you create a feature that allow me to choose the range of notes on treble and bass that I will practice?

I ask it because people like me, or newbies, are not capable to play with too much movement of the hands, at least for somewhile.

Thanks for all, you did a great job.

Marcos

**Comment by leafo** [comment]
sure, this is probably the same request as #6

**Comment by leafo** [comment]
going to close this in favor of #6, will be deployed soon
