### ISSUE TITLE
Flat notes not working in Key Signatures with Flats in Staff Training

### ISSUE THREAD

**Issue by Markrosoft123** [leafo/sightreading.training#70]
The Staff Training page is working great for me if I stay in the key of C or a key that has sharps. However, if I choose a key signature that has flats it is not accepting those notes. For example, a A-flat pops up on the staff and if I hit it, it says the note is incorrect. If I play a A-natural it still says it's incorrect. If I play an A-sharp it does the same. So basically anytime it gets to the note that should be a flat note, the program stops because there's no way to play the correct note and move forward. 

The work around is just to use C or key signatures with sharps but it would be great to train in key signatures that have flats too. Thanks for your help!

**Comment by AmolosRicha1** [comment]
I have the same problem with the flat keys, currently they don't seem to be working. The software is marking correct input as wrong.

**Comment by ddTech** [comment]
Hi, 
I've fixed that in my version. 
See  #71 

Regards Frank

**Comment by leafo** [comment]
this is fixed in master, will be deploying soon
