### ISSUE TITLE
Flats don't work for Yamaha P-115

### ISSUE THREAD

**Issue by tjboller** [leafo/sightreading.training#76]
anyone else having this issue?

**Comment by tjboller** [comment]
actually it works for the chord setting "staff" but for no others

**Comment by ddTech** [comment]
yes, everyone has this issue. 
leafo reported that he has fixed it by now but it seems, he has not yet updated the live server.
You might like so have a look into my notes here:   #71

**Comment by tjboller** [comment]
wow very impressive @ddTech . Hopefully leafo would be open to you submitting a MR with your improvements - open source software is awesome
