### ISSUE TITLE
No Sound output suddenly today

### ISSUE THREAD

**Issue by HHHorus** [leafo/sightreading.training#98]
Hi, for no reason I had no sound output using my Keystation88 midi keyboard in Chrome or Edge, but the software responds to my input.

I tested midi connection in Cubase, Flowkey online and online in Chrome in Pianu and all are working and give sound output.

The online "internal piano" keyboard gives sound output using the mouse.

I had to use the sound output via Pianu website whilst I practiced in another tab on sightreading.training,

Hope you can help

**Comment by leafo** [comment]
when you say "no sound," what exactly are you expecting to make sound? The keystation is a midi only controller, so something else would have been making sound. Are you expecting the built in piano to sound or something as a result of a midi event like an external device or software synthesizer?

You can also check your browser console to see if there are any warnings there.

**Comment by HHHorus** [comment]
The 2 websites Flowplay and Pianu work the same way and I always assumed 
they used some default piano midi sound windows offers.

Yes I'm expecting this to happen with your website as it always has .

I don't see any warnings no.

So do Flowplay and Pianu use windows built in piano or have one 
incorporated on the website. How does sightreading.training produce 
sound?

------ Original Message ------
From: "leaf" ***@***.***>
To: "leafo/sightreading.training" 
***@***.***>
Cc: "HHHorus" ***@***.***>; "Author" 
***@***.***>
Sent: 16/03/2021 18:11:10
Subject: Re: [leafo/sightreading.training] No Sound output suddenly 
today (#98)

**Comment by HHHorus** [comment]
![Capture2](https://user-images.githubusercontent.com/80779039/111391671-00740600-86ad-11eb-9999-c6e4ad15ee90.JPG)

Sorry , now I've checked the browser console and can see a few errors and warnings.
This is just after refreshing the page

**Comment by HHHorus** [comment]
Well this gave me an opportunity to check out VirtualMidisynth as I read some had had problems with the Microsoft GS wavetable synth. And it works, I now have sound BUT with with obvious latency. So ideally I'd like the MIcrosoft GS wavetable to work if that's what I had been using.

**Comment by leafo** [comment]
I'm going to close this ticket as there is nothing actionable for me here without a stack trace on the error. If I had to guess, your browser was potentially blocking access to some web API. If you were loading the site in incognito mode, or have enabled other strict security settings, that could be a cause.
